---
- name: Running opencontrail init contrail for neutron server
  vars:
    neutron_server: "{{ neutron_services['neutron-server'] }}"
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    detach: False
    image: "{{ neutron_opencontrail_init_image_full }}"
    labels:
      BOOTSTRAP:
    name: "bootstrap_neutron_opencontrail_plugin"
    restart_policy: "never"
    volumes: "{{ neutron_server.volumes }}"
  when:
    - neutron_plugin_agent == 'opencontrail'
    - neutron_server.enabled | bool
    - neutron_server.host_in_groups | bool
  run_once: True
  delegate_to: "{{ groups[neutron_server.group][0] }}"
